/* ===== caseirao-adm-rebuild-v31-script ===== */
(()=>{
 const primaryOrder=['pedidos','mesas','producao','entregas'];
 const managementOrder=['visao','caixa','cashback','premiado','fidelidade','gestao','relatorios','promocoes','produtos','adicionais','bairros','cupons','banner','funcionarios','loja'];
 const labels={visao:'⌂ Visão geral',pedidos:'⚡ Pedidos',mesas:'▦ Mesas',producao:'🍔 Produção',entregas:'🛵 Entregas',caixa:'$ Caixa',cashback:'◈ Cashback',premiado:'🎁 Pedido premiado',fidelidade:'★ Fidelidade',gestao:'▥ Indicadores',relatorios:'↻ Histórico',promocoes:'🔥 Promoções',produtos:'🍔 Produtos',adicionais:'+ Adicionais',bairros:'⌖ Bairros e taxas',cupons:'% Cupons',banner:'▣ Banners',funcionarios:'♟ Funcionários',loja:'⚙ Configurações'};
 function enhanceLauncher(){const card=document.querySelector('.teamLauncherCard');if(!card||card.dataset.rebuilt)return;card.dataset.rebuilt='1';const logo=card.querySelector('.teamLogo'),h1=card.querySelector('h1'),p=card.querySelector('p'),choices=[...card.querySelectorAll('.teamChoice')];const intro=document.createElement('div');intro.className='teamLauncherIntro';const copy=document.createElement('div');copy.innerHTML='<span class="teamLauncherKicker">CENTRAL DE OPERAÇÃO</span>';copy.append(h1,p);const live=document.createElement('span');live.className='teamLauncherLive';live.textContent='SISTEMA CONECTADO';intro.append(logo,copy,live);const grid=document.createElement('div');grid.className='teamAccessGrid';choices.forEach(choice=>grid.appendChild(choice));card.prepend(intro);intro.after(grid)}
 function enhanceLogin(){const sheet=document.querySelector('.sheet.full');const login=sheet?.querySelector('.loginbox');if(!sheet||!login||sheet.classList.contains('admWorkspace'))return;sheet.classList.add('admLoginPremium');if(!login.querySelector('.admLoginBrand'))login.insertAdjacentHTML('afterbegin','<div class="admLoginBrand">CB</div><div style="text-align:center;margin-bottom:18px"><b style="font-size:20px">Central Administrativa</b><div class="mini" style="margin-top:5px">Acesso protegido do Caseirão</div></div>')}
 function buildWorkspace(){const sheet=document.querySelector('.sheet.full'),head=sheet?.querySelector(':scope>.adminHead'),bar=sheet?.querySelector(':scope>.admbar'),content=sheet?.querySelector('#admContent');if(!sheet||!head||!bar||!content||bar.dataset.rebuilt)return;bar.dataset.rebuilt='1';sheet.classList.add('admWorkspace');const buttons=[...bar.querySelectorAll('button[data-tab]')];buttons.forEach(button=>{if(labels[button.dataset.tab])button.textContent=labels[button.dataset.tab]});const byTab=tab=>buttons.find(button=>button.dataset.tab===tab);const primary=document.createElement('nav');primary.className='admPrimaryNav';primary.setAttribute('aria-label','Operação principal');primaryOrder.forEach(tab=>{const button=byTab(tab);if(button)primary.appendChild(button)});const manageNav=document.createElement('nav');manageNav.className='admManagementNav';managementOrder.forEach(tab=>{const button=byTab(tab);if(button)manageNav.appendChild(button)});buttons.filter(button=>!primary.contains(button)&&!manageNav.contains(button)).forEach(button=>manageNav.appendChild(button));const aside=document.createElement('aside');aside.className='admManagement';aside.innerHTML='<div class="admManagementTitle">GESTÃO E CONFIGURAÇÕES</div>';aside.appendChild(manageNav);const main=document.createElement('main');main.className='admWorkspaceMain';main.appendChild(content);const body=document.createElement('div');body.className='admWorkspaceBody';body.append(aside,main);const toggle=document.createElement('button');toggle.type='button';toggle.className='admManagementToggle';toggle.innerHTML='☰ Mais';toggle.setAttribute('aria-expanded','false');toggle.onclick=()=>{aside.classList.toggle('open');const opened=aside.classList.contains('open');toggle.setAttribute('aria-expanded',opened?'true':'false');toggle.innerHTML=opened?'× Fechar':'☰ Mais'};bar.replaceChildren(primary,toggle,body);const active=bar.querySelector('button.on');if(active&&manageNav.contains(active)&&matchMedia('(max-width:900px)').matches)aside.classList.add('open')}
 const finalRenderAdminBase=renderAdmin;renderAdmin=function(){const result=finalRenderAdminBase();queueMicrotask(buildWorkspace);return result};
 const observer=new MutationObserver(()=>{enhanceLauncher();enhanceLogin();buildWorkspace()});observer.observe(document.body,{subtree:true,childList:true});enhanceLauncher();
 document.addEventListener('click',event=>{const button=event.target.closest?.('.admManagementNav button[data-tab]');if(!button||!matchMedia('(max-width:900px)').matches)return;setTimeout(()=>document.querySelector('.admManagement')?.classList.remove('open'),80)},true);
})();

/* ===== caseirao-admin-premium-v30-script ===== */
(()=>{
 const cashCall=(action,payload={})=>api('cashback-api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:sessionStorage.getItem('caseirao_admin_pin')||'',action,payload})});
 const cashMoney=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 /* Mensagens de status: usa somente o painel nativo do app.js para evitar duplicidade. */
 async function renderCashbackAdmin(box){
  box.innerHTML='<div class="empty">Carregando programa de cashback...</div>';
  try{
   const r=await cashCall('admin_snapshot'),s=r.settings||{},customers=r.customers||[],totalBalance=customers.reduce((n,c)=>n+Number(c.cashback_balance||0),0),totalEarned=customers.reduce((n,c)=>n+Number(c.cashback_earned||0),0),participants=customers.filter(c=>Number(c.cashback_earned||0)>0||Number(c.cashback_balance||0)>0||Number(c.cashback_cycle_count||0)>0),cycleTarget=1;
   box.innerHTML=`<section class="cashbackAdminHero"><small>CLUBE CASEIRÃO</small><h2>Cashback em toda compra</h2><p>Todo pedido entregue gera ${esc(s.cashback_percent||5)}% de cashback para o cliente, calculado em centavos sobre o valor elegível.</p><div class="cashbackKpis"><div class="cashbackKpi"><span>SALDO DOS CLIENTES</span><b>${cashMoney(totalBalance)}</b></div><div class="cashbackKpi"><span>TOTAL GERADO</span><b>${cashMoney(totalEarned)}</b></div><div class="cashbackKpi"><span>PARTICIPANTES</span><b>${participants.length}</b></div></div></section>
   <section class="cashbackConfig"><div class="sectionTitle">Regras do Cashback</div><label class="cashbackStatusToggle"><input id="cashEnabled" type="checkbox" ${s.cashback_enabled?'checked':''}> Cashback ativo</label><div class="cashbackConfigGrid">
   <div class="field"><label>Cashback (%)</label><input id="cashPercent" class="in" inputmode="decimal" value="${esc(s.cashback_percent)}"></div>
   <div class="field"><label>Mínimo de saldo para usar</label><input id="cashMinimum" class="in" inputmode="decimal" value="${esc(s.cashback_min_redeem)}"></div>
   <div class="field"><label>Máximo que pode usar (%)</label><input id="cashMax" class="in" inputmode="decimal" value="${esc(s.cashback_max_redeem_percent)}"></div>
   <div class="field"><label>Validade do crédito (dias)</label><input id="cashExpiry" class="in" inputmode="numeric" value="${esc(s.cashback_expiry_days)}"></div></div>
   <div class="operationHint">Regra atual: todo pedido entregue gera cashback. O valor é calculado pelo percentual acima e creditado em centavos. Pedidos cancelados não geram cashback.</div><button id="saveCashback" class="primary">SALVAR REGRAS</button></section>
   <section class="cashbackCustomers"><div class="sectionTitle">Clientes e progresso do ciclo</div><input id="cashbackSearch" class="in cashbackSearch" placeholder="Buscar nome ou telefone"><div id="cashbackCustomerList"></div></section>`;
   const draw=q=>{$('#cashbackCustomerList').innerHTML=customers.filter(c=>!q||`${c.name} ${c.phone}`.toLowerCase().includes(q)).map(c=>{const cycle=Math.min(cycleTarget,Number(c.cashback_cycle_count||0));return `<div class="cashbackCustomer"><div><strong>${esc(c.name||'Cliente')}</strong><span>${esc(c.phone||'')} • ${Number(c.order_count||0)} pedidos no histórico • cashback em toda compra</span></div><div class="cashbackCustomerBalance">${cashMoney(c.cashback_balance)}</div><button class="cashbackAdjust" data-cash-adjust="${c.id}" data-cash-name="${esc(c.name||'Cliente')}">AJUSTAR</button></div>`}).join('')||'<div class="empty">Nenhum cliente encontrado.</div>';document.querySelectorAll('[data-cash-adjust]').forEach(button=>button.onclick=async()=>{const raw=prompt(`Ajuste de cashback para ${button.dataset.cashName}. Use valor positivo para adicionar ou negativo para retirar:`);if(raw===null)return;const amount=Number(String(raw).replace(',','.'));if(!Number.isFinite(amount)||!amount)return alert('Informe um valor válido.');const description=prompt('Motivo do ajuste:','Ajuste autorizado pelo ADM')||'Ajuste autorizado pelo ADM';try{button.disabled=true;await cashCall('adjust',{customer_id:button.dataset.cashAdjust,amount,description});await renderCashbackAdmin(box);showAppToast('Saldo de cashback atualizado.','ok')}catch(e){button.disabled=false;alert(e.message||String(e))}})};
   draw('');$('#cashbackSearch').oninput=e=>draw(e.target.value.trim().toLowerCase());
   $('#saveCashback').onclick=async()=>{const button=$('#saveCashback');try{button.disabled=true;button.textContent='SALVANDO...';await cashCall('save_settings',{cashback_enabled:$('#cashEnabled').checked,cashback_percent:num($('#cashPercent').value),cashback_every_n_orders:1,cashback_min_order:0,cashback_max_per_order:0,cashback_min_redeem:num($('#cashMinimum').value),cashback_max_redeem_percent:num($('#cashMax').value),cashback_expiry_days:Number($('#cashExpiry').value)||0,cashback_allow_with_coupon:true,cashback_allow_with_promo:true});await renderCashbackAdmin(box);showAppToast('Regras do cashback salvas.','ok')}catch(e){button.disabled=false;button.textContent='TENTAR NOVAMENTE';alert(e.message||String(e))}}
  }catch(e){box.innerHTML=`<div class="err">${esc(e.message||String(e))}</div>`}
 }
 const renderAdminCashBase=renderAdmin;renderAdmin=function(){const out=renderAdminCashBase();const bar=document.querySelector('.admbar');if(bar&&!bar.querySelector('[data-tab="cashback"]')){const button=document.createElement('button');button.dataset.tab='cashback';button.className=adminTab==='cashback'?'on':'';button.textContent='Cashback';button.onclick=()=>{adminTab='cashback';renderAdmin()};const loyalty=bar.querySelector('[data-tab="fidelidade"]');loyalty?loyalty.after(button):bar.appendChild(button)}return out};
 const renderAdminTabCashBase=renderAdminTab;renderAdminTab=function(){if(adminTab==='cashback'){const box=$('#admContent');if(box)renderCashbackAdmin(box);return}return renderAdminTabCashBase()};
})();
